### ISSUE TITLE
How to use this extension, I tried using it, but it does not do anything

### ISSUE THREAD

**Issue by naqushab** [joshcai/leetcode-sync-chrome#1]
Hi @joshcai ,
Thank you for Leetcode sync, I searched around and found this as well, which can help updating the Leetcode variables automatically. Is there a way we can use this? I donot see any readme related to it
I tried installing yarn
then yarn install
and then running yarn build

It did give me a build folder but loading it in Chrome does nothing.

**Comment by joshcai** [comment]
Hi @naqushab, apologies for not having any documentation - I had intended to publish this to the Chrome Web Store but ended up not getting around to it. I'll see if I can find some time in the upcoming weeks to do that.

Can you try downloading the zip file directly from the releases and uploading it for now if you want to use it today?
https://github.com/joshcai/leetcode-sync/issues/7#issuecomment-779557829 has some more information.

**Comment by naqushab** [comment]
Thanks @joshcai for your prompt response. Yes, I tried it and it is working fine. 
Thank you for your help. 🙂
